version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package
      # Move the JAR file from target/ to the root directory
      - echo "Moving JAR file to root folder"
      - mv target/*.jar .  # Moves the .jar file to the root directory of the build artifact

artifacts:
  files:
    - "*.jar"  # Specify that the .jar file is the artifact to be deployed